<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Walk-in booking · Carolina</title><link rel="stylesheet" href="{{ asset('css/admin.css') }}?v={{ filemtime(public_path('css/admin.css')) }}"><style>
.walkin-card{max-width:820px}.walkin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.walkin-grid label{display:grid;gap:7px;font-size:12px;font-weight:700;color:var(--muted)}.walkin-grid input,.walkin-grid select{border:1px solid var(--line);border-radius:7px;padding:11px;background:#fff;color:var(--ink);font:inherit}.walkin-grid .full{grid-column:1/-1}.walkin-help{margin:0;color:var(--muted);font-size:13px}.walkin-submit{border:0;border-radius:7px;padding:13px;background:var(--orange);color:#fff;font:700 14px system-ui;cursor:pointer}@media(max-width:680px){.walkin-grid{grid-template-columns:1fr}}
</style></head>
<body><div class="admin-shell">@include('admin.partials.sidebar')
<main class="admin-main"><header class="admin-topbar"><div><p class="admin-kicker">FRONT DESK</p><h1>New walk-in</h1><p class="admin-subtitle">Create a confirmed stay after checking the exact arrival and departure times.</p></div></header>
@if($errors->any())<div class="admin-flash" style="background:#fbe3e0;color:#a84336">{{ $errors->first() }}</div>@endif
<section class="panel walkin-card"><form method="POST" action="{{ route('admin.walk-ins.store') }}" class="walkin-grid">@csrf
<label class="full">Room<select name="room_id" required><option value="">Choose a room</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(old('room_id') == $room->id)>{{ $room->name }} · up to {{ $room->guests }} guests · ₱{{ number_format($room->price_per_night) }} {{ $room->rate_label }}</option>@endforeach</select></label>
<label>Guest name<input name="guest_name" value="{{ old('guest_name') }}" required></label><label>Phone number<input name="guest_phone" value="{{ old('guest_phone') }}" required></label><label>Email (optional)<input type="email" name="guest_email" value="{{ old('guest_email') }}"></label><label>Guests<input type="number" name="guests" min="1" value="{{ old('guests',1) }}" required></label>
<label>Check-in date<input type="date" name="check_in" min="{{ now()->toDateString() }}" value="{{ old('check_in',now()->toDateString()) }}" required></label><label>Check-in time<input type="time" name="check_in_time" value="{{ old('check_in_time',now()->format('H:i')) }}" required></label><label>Check-out date<input type="date" name="check_out" min="{{ now()->addDay()->toDateString() }}" value="{{ old('check_out',now()->addDay()->toDateString()) }}" required></label><label>Check-out time<input type="time" name="check_out_time" value="{{ old('check_out_time',now()->format('H:i')) }}" required></label>
<p class="walkin-help full">This is a staff-confirmed booking. No online payment is collected or recorded here. The room is checked again for conflicts when you submit.</p><button class="walkin-submit full" type="submit">Confirm walk-in booking</button>
</form></section></main></div></body></html>
